inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
