source "https://rubygems.org"

gem "rails", "~> 8.0"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "bcrypt", "~> 3.1.7"

# GraphQL
gem "graphql", "~> 2.4"

# Resourcemonitor dependencies
gem "pundit"
gem "aasm"
gem "rack-attack"
gem "rack-cors"

# Windows does not include zoneinfo files
gem "tzinfo-data", platforms: %i[windows jruby]

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "simplecov", require: false
end

group :test do
  gem "shoulda-matchers"
  gem "pundit-matchers"
end
